const initialOrders = [
  {
    id: "ORD-1001",
    customer: {
      name: "Rahul Mehta",
      email: "rahul.mehta@example.com",
      phone: "+91 9876543210",
      address: "123 MG Road, Delhi 110001",
    },
    items: [
      {
        id: "P-101",
        name: "Basmati Rice",
        price: 120,
        quantity: 2,
        image: null,
      },
      {
        id: "P-205",
        name: "Brown Bread",
        price: 40,
        quantity: 1,
        image: null,
      },
    ],
    date: "2023-06-10",
    total: 280,
    status: "Pending",
    paymentStatus: "Unpaid",
    paymentMethod: "Online",
    deliveryDate: "2023-06-12",
    notes: "Leave at the security gate",
  },
  {
    id: "ORD-1002",
    customer: {
      name: "Anjali Sharma",
      email: "anjali.sharma@example.com",
      phone: "+91 9123456789",
      address: "456 Lake View, Mumbai 400001",
    },
    items: [
      {
        id: "P-110",
        name: "Almond Milk",
        price: 199,
        quantity: 1,
        image: null,
      },
      {
        id: "P-215",
        name: "Multigrain Atta",
        price: 350,
        quantity: 1,
        image: null,
      },
      {
        id: "P-320",
        name: "Dark Chocolate",
        price: 150,
        quantity: 3,
        image: null,
      },
    ],
    date: "2023-06-12",
    total: 999,
    status: "Shipped",
    paymentStatus: "Paid",
    paymentMethod: "UPI",
    deliveryDate: "2023-06-14",
    notes: "",
  },
  {
    id: "ORD-1003",
    customer: {
      name: "Vikram Singh",
      email: "vikram.singh@example.com",
      phone: "+91 7654321098",
      address: "789 Pine Rd, Bangalore 560001",
    },
    items: [
      {
        id: "P-105",
        name: "Organic Bananas",
        price: 49,
        quantity: 5,
        image: null,
      },
      {
        id: "P-208",
        name: "Fresh Spinach",
        price: 39,
        quantity: 2,
        image: null,
      },
      {
        id: "P-310",
        name: "Greek Yogurt",
        price: 129,
        quantity: 2,
        image: null,
      },
    ],
    date: "2023-06-13",
    total: 581,
    status: "Delivered",
    paymentStatus: "Paid",
    paymentMethod: "COD",
    deliveryDate: "2023-06-15",
    notes: "",
  },
];

export default initialOrders;
